#!/bin/sh
# AC 04-05-2015 exécuté sous jenkins sans ssh (serveur identique) 
#ssh app@APP.SERVER.IP.ADDRESS <<EOF
  cd /var/www/git/test-jenkins
  git pull
  npm install --production
  forever restartall
  exit
#EOF
